
quartzVersion = 3.0.0-SNAPSHOT

fullname=quartz-scheduler
name=quartz
version=$quartzVersion

slf4jVersion = 2.0.17
mongodbDriverVersion = 5.6.4
junitBomVersion = 6.0.1
mockitoVersion = 5.20.0
testcontainersVersion = 1.21.4
jakartaXmlBindVersion = 4.0.5
jakartaTransactionVersion = 2.0.1
jakartaServletVersion = 6.1.0
jakartaJmsVersion = 3.1.0
jakartaMailVersion = 2.1.5
jakartaEjbVersion = 4.0.1
jbossVersion = 4.0.2
commonjVersion = 1.0
commonsIoVersion = 2.22.0
hamcrestVersion = 3.0
logbackVersion = 1.5.21

# For nexus-publish plugin
sonatypeUsername = OVERRIDE_ME
sonatypePassword = OVERRIDE_ME
