plugins {
    id 'java-library'
    id 'maven-publish'
    id 'biz.aQute.bnd.builder'
}

repositories {
    mavenCentral()
}

publishing {
    publications {
        getByName('maven').pom.description = 'Quartz Enterprise Job Scheduler'
    }
}

dependencies {
    compileOnly project(':quartz-stubs')
    compileOnly "jboss:jboss-common:$jbossVersion"
    compileOnly "jboss:jboss-minimal:$jbossVersion"
    compileOnly "jboss:jboss-system:$jbossVersion"
    compileOnly "jboss:jboss-jmx:$jbossVersion"
    compileOnly "org.apache.geronimo.specs:geronimo-commonj_1.1_spec:$commonjVersion"

    implementation "org.slf4j:slf4j-api:$slf4jVersion"
    implementation "org.mongodb:mongodb-driver-sync:$mongodbDriverVersion"

    implementation "jakarta.xml.bind:jakarta.xml.bind-api:$jakartaXmlBindVersion"

    compileOnly "jakarta.transaction:jakarta.transaction-api:$jakartaTransactionVersion"
    testImplementation "jakarta.transaction:jakarta.transaction-api:$jakartaTransactionVersion"
    compileOnly "jakarta.servlet:jakarta.servlet-api:$jakartaServletVersion"

    testImplementation 'org.hamcrest:hamcrest:' + hamcrestVersion
    testImplementation(platform("org.junit:junit-bom:$junitBomVersion"))
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation "org.mockito:mockito-core:$mockitoVersion"
    testImplementation "org.testcontainers:mongodb:$testcontainersVersion"
    testImplementation "org.testcontainers:junit-jupiter:$testcontainersVersion"
    testImplementation "org.ow2.asm:asm:9.9"
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly "ch.qos.logback:logback-classic:$logbackVersion"
}

test {
    useJUnitPlatform(){
        includeEngines("junit-jupiter")
    }
    maxParallelForks 1
    forkEvery 1
}

java {
    withJavadocJar()
    withSourcesJar()
}

javadoc {
    options {
        docTitle = "Quartz Enterprise Job Scheduler $project.version API"
        encoding = 'UTF-8'
        outputLevel = JavadocOutputLevel.QUIET
        splitIndex = false
        author = true;
        windowTitle = "Quartz Enterprise Job Scheduler $project.version API"
        bottom = 'Copyright IBM Corp. 2024, 2025'
    }
}


processResources {
    filesMatching('**/quartz-build.properties') {
        expand([version: project.version, fullname: project.fullname, name: project.name])
    }
}
