plugins {
    id 'java-library'
    id 'maven-publish'
    id 'biz.aQute.bnd.builder'
}

dependencies {
    implementation project(':quartz')

    implementation "org.slf4j:slf4j-api:$slf4jVersion"

    compileOnly "jakarta.jms:jakarta.jms-api:$jakartaJmsVersion"
    compileOnly "jakarta.mail:jakarta.mail-api:$jakartaMailVersion"
    compileOnly "jakarta.ejb:jakarta.ejb-api:$jakartaEjbVersion"
    compileOnly 'org.glassfish.corba:rmic:5.0.2'

    testImplementation "jakarta.transaction:jakarta.transaction-api:$jakartaTransactionVersion"
    testImplementation "commons-io:commons-io:$commonsIoVersion"
    testImplementation(platform("org.junit:junit-bom:$junitBomVersion"))
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'junit:junit:4.13.2'
    testRuntimeOnly 'org.junit.vintage:junit-vintage-engine'
    testImplementation "org.hamcrest:hamcrest:$hamcrestVersion"
    testImplementation "jakarta.mail:jakarta.mail-api:$jakartaMailVersion"
    testImplementation 'org.subethamail:subethasmtp:3.1.7'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testRuntimeOnly "ch.qos.logback:logback-classic:$logbackVersion"
}

java {
    withJavadocJar()
    withSourcesJar()
}

test {
    useJUnitPlatform()
    maxParallelForks 1
    forkEvery 1
}

publishing {
    publications {
        getByName('maven').pom.description = 'Quartz Enterprise Job Scheduler - additional library of ready to use Jobs'
    }
}
